#include <rcc.h>

void GPIOA_CLK_ENABLE()
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPA_CLK_EN;
}

void GPIOB_CLK_ENABLE()
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPB_CLK_EN;
}

void GPIOC_CLK_ENABLE()
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPC_CLK_EN;
}

void GPIOD_CLK_ENABLE()
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPD_CLK_EN;
}

void GPIOA_CLK_DISABLE()
{
    RCC->APB2ENR &= RCC_APB2ENR_IOPA_CLK_DIS;
}

void GPIOB_CLK_DISABLE()
{
    RCC->APB2ENR &= RCC_APB2ENR_IOPB_CLK_DIS;
}

void GPIOC_CLK_DISABLE()
{
    RCC->APB2ENR &= RCC_APB2ENR_IOPC_CLK_DIS;
}

void GPIOD_CLK_DISABLE()
{
    RCC->APB2ENR &= RCC_APB2ENR_IOPD_CLK_DIS;
}

void TIM1_ENABLE()
{
    RCC->APB2ENR |= RCC_APB2ENR_TIM1_ENABLE;
}

void TIM2_ENABLE()
{
    RCC->APB1ENR |= RCC_APB1ENR_TIM2_ENABLE;
}

void TIM3_ENABLE()
{
    RCC->APB1ENR |= RCC_APB1ENR_TIM3_ENABLE;
}

void TIM4_ENABLE()
{
    RCC->APB1ENR |= RCC_APB1ENR_TIM4_ENABLE;
}

void USART1_ENABLE()
{
    /* Enable USART1 and Alternate function clock */
    RCC->APB2ENR |= (RCC_APB2ENR_USART1_ENABLE);
    RCC->APB2ENR |= (RCC_APB2ENR_AFIO_ENABLE);
}

void USART2_ENABLE()
{
    RCC->APB1ENR |= (RCC_APB1ENR_USART2_ENABLE);
    RCC->APB2ENR |= (RCC_APB2ENR_AFIO_ENABLE);
}

void USART3_ENABLE()
{
    RCC->APB1ENR |= (RCC_APB1ENR_USART3_ENABLE);
    RCC->APB2ENR |= (RCC_APB2ENR_AFIO_ENABLE);
}

void USART4_ENABLE()
{
    RCC->APB1ENR |= (RCC_APB1ENR_USART4_ENABLE);
}

void USART5_ENABLE()
{
    RCC->APB1ENR |= (RCC_APB1ENR_USART5_ENABLE);
}

void SysClockConfig()
{
    /* Enable HSI and wait for it to become ready */
    RCC->CR |= RCC_CR_HSI_ON;
    while((RCC->CR & RCC_CR_HSI_READY) != RCC_CR_HSI_READY);

}
